<?php

namespace HDViegas\NFSeTinus;

class RpsConstants
{
	const VERSION_1_0 = '1.00';

	const TIPO_RPS = 1;
	const TIPO_RPS_MISTA = 2;
	const TIPO_CUPOM = 3;

	const NATUREZA_OPERACAO_TRIBUTACAO_MUNICIPIO = 1;
	const NATUREZA_OPERACAO_TRIBUTACAO_FORA_MUNICIPIO = 2;
	const NATUREZA_OPERACAO_ISENCAO = 3;
	const NATUREZA_OPERACAO_IMUNE = 4;
	const NATUREZA_OPERACAO_EXIGIBILIDADE_SUSPENSA_DECISAO_JUDICIAL = 5;
	const NATUREZA_OPERACAO_EXIGIBILIDADE_SUSPENSA_PROCEDIMENTO_ADMINISTRATIVO = 6;

	const REGIME_ESPECIAL_TRIBUTACAO_MICROEMPRESA_MUNICIPAL = 1;
	const REGIME_ESPECIAL_TRIBUTACAO_ESTIMATIVA = 2;
	const REGIME_ESPECIAL_TRIBUTACAO_SOCIEDADE_PROFISSIONAIS = 3;
	const REGIME_ESPECIAL_TRIBUTACAO_COOPERATIVA = 4;
	const REGIME_ESPECIAL_TRIBUTACAO_MEI_SIMPLES_NACIONAL = 5;
	const REGIME_ESPECIAL_TRIBUTACAO_ME_EPP_SIMPLES_NACIONAL = 6;

	const STATUS_NORMAL = 1;
	const STATUS_CANCELADO = 2;

	const SIM = 1;
	const NAO = 2;

}